[2023-05-05T11:24:28.440+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-05-05T11:24:28.445+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2023-05-04T00:00:00+00:00 [queued]>
[2023-05-05T11:24:28.446+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-05-05T11:24:28.454+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-05-04 00:00:00+00:00
[2023-05-05T11:24:28.459+0000] {standard_task_runner.py:57} INFO - Started process 195 to run task
[2023-05-05T11:24:28.463+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2023-05-04T00:00:00+00:00', '--job-id', '1122', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpb09uu8hn']
[2023-05-05T11:24:28.465+0000] {standard_task_runner.py:85} INFO - Job 1122: Subtask create_postgres_table
[2023-05-05T11:24:28.520+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2023-05-04T00:00:00+00:00 [running]> on host 39440b36e721
[2023-05-05T11:24:28.582+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jose-holgado' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-04T00:00:00+00:00'
[2023-05-05T11:24:28.583+0000] {sql.py:262} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt DATE,
                dag_id CHARACTER VARYING,
                PRIMARY KEY (dt, dag_id)
            )
        
[2023-05-05T11:24:28.591+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-05-05T11:24:28.670+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-05-05T11:24:38.688+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2023-05-05T11:24:38.715+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20230504T000000, start_date=20230505T112428, end_date=20230505T112438
[2023-05-05T11:24:38.736+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1122 for task create_postgres_table (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 195)
[2023-05-05T11:24:38.761+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-05T11:24:38.778+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
